### ISSUE TITLE
Allow throwing anything

### ISSUE THREAD

**Issue by wyrfel** [MatthiasKunnen/rxjs-throw-if#3]
Hi Matthias,

i came across this and it's exactly what I needed, except...restricting the second parameter to a string limits the use of this operator. The built-in RxJS error operators don't have this limitation, so removing it would make this operator more consistent with the rest of RxJS and broaden its application scope.

**Comment by MatthiasKunnen** [comment]
Thank you for your suggestion! I've implemented it together with support for dynamic errors and released it under v2.2.0. For RxJS v7 I'll release 3.0.0.
